### ISSUE TITLE
TODO (Next.js)

### ISSUE THREAD

**Issue by RikuOta** [sumiren/bookapp#5]
## 優先度: 高

- [x] エラーハンドリング
- [x] 未ログインの場合はログイン画面へリダイレクト
- [x] 404 ページの作成
- [x] レスポンシブ対応
- [x] Mantine と Tailwind の統合 (Color、Breakpoints、Spacing、Reset CSS)

## 優先度: 中

- [ ] ログアウト時にセッションをクリア (現状は暫定処理で /login にリダイレクトするだけ)
- [ ] 認証情報を API から取得 (現状は暫定処理で Cookie から取得)
- [ ] ログイン・アカウント登録時のフォームのバリデーションを厳密にする

## 優先度: 低

- [x] 通知の実装 (追加時、削除時など)
- [ ] アニメーションの実装 (画面遷移時など)
- [ ] ユーザ名を表示
- [ ] 書籍・TODO が0件時の表示
- [ ] Lint の導入
